---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-08-23-08-2019 20:01
---

IdeaMassMainViewLayout = {
    _containerView = nil,
    _navigationBar = nil,
    _titleLabel = nil,
    _backBtn = nil,
    _shareBtn = nil,
    _headerView = nil,
    _waterfallView = nil
}

---@public
function setup()
    setupSubviews()
end

---@private
function setupSubviews()
    setupConstant()
    setupContainerView()
    setupTitleView()
    setupHeaderView()
end


function setupConstant()
    require('MMLuaKitGallery.Constant')
end

---容器视图
---@private
function setupContainerView()
    local containerView = LinearLayout(LinearType.VERTICAL)
    containerView:width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT):bgColor(_Color.White)
    window:addView(containerView)

    if System:iOS() then
        containerView:marginTop(window:statusBarHeight())
    end

    IdeaMassMainViewLayout._containerView = containerView
end

---导航栏视图
---@private
function setupTitleView()
    --导航栏
    navigationBar = View():width(window:width()):height(_NaviBarHeight)
    local titleLabel = Label()
    IdeaMassMainViewLayout._titleLabel = titleLabel
    titleLabel:width(MeasurementType.WRAP_CONTENT):height(MeasurementType.WRAP_CONTENT):setGravity(Gravity.CENTER)
    titleLabel:text("灵感集"):textAlign(TextAlign.CENTER)
    titleLabel:setTextFontStyle(FontStyle.NORMAL)
    titleLabel:fontSize(16)
    navigationBar:addView(titleLabel)
    IdeaMassMainViewLayout._navigationBar = navigationBar
    IdeaMassMainViewLayout._containerView:addView(navigationBar)

    --返回
    local backBtn = ImageView():width(22):height(22):marginLeft(20):setGravity(MBit:bor(Gravity.LEFT, Gravity.CENTER_VERTICAL))
    backBtn:image("icon_back")
    navigationBar:addView(backBtn)
    backBtn:onClick(function()
        Navigator:closeSelf(AnimType.Default)
    end)
    IdeaMassMainViewLayout._backBtn = backBtn;

    --分享
    local shareBtn = ImageView():width(22):height(22):marginRight(20):setGravity(MBit:bor(Gravity.RIGHT, Gravity.CENTER_VERTICAL))
    shareBtn:image("1567316383469-minshare")
    navigationBar:addView(shareBtn)
    IdeaMassMainViewLayout._shareBtn = shareBtn;

end

---header设置
function setupHeaderView()
    local headerView = require('MMLuaKitGallery.IdeaMassViewHeaderView'):new()
    IdeaMassMainViewLayout._containerView:addView(headerView.HeaderView)
    IdeaMassMainViewLayout._headerView = headerView
end


--- 主页面布局
setup()
