---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-08-23-08-2019 20:01
---

MainLayout = {
    _tabBarContainerView = nil,
    _tabBarContentView = nil,
    _tabBar = nil,
    _homePagerContainerView = nil,
    _homePagerSegement = nil,
    _homePagerViewPager = nil,
    _homePagerViewPagerAdadpter = nil,
    _placeHolderView = nil
}

---@public
function setup()
    setupMacros()
    setupTabBar()
    setupHomePagerView()
end

function setupMacros()
    require("MMLuaKitGallery.Constant")
end

---@private
function setupTabBar()
    local containerView = LinearLayout(LinearType.VERTICAL):width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT)
    MainLayout._tabBarContainerView = containerView
    window:addView(containerView)

    local contentView = View():width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT):setGravity(Gravity.CENTER_HORIZONTAL)
    if System:iOS() then
        contentView:marginTop(window:statusBarHeight())
    end

    MainLayout._tabBarContentView = contentView
    containerView:addView(contentView)

    local normalImages = Array()
    normalImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829621-hom.png")
    normalImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829567-disc.png")
    normalImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829827-plus.png")
    normalImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829551-msg.png")
    normalImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877767583-min.png")

    local selectImages = Array()
    selectImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829589-hom_d.png")
    selectImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829612-disc_d.png")
    selectImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829827-plus.png")
    selectImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877829774-msg_d.png")
    selectImages:add("https://s.momocdn.com/w/u/others/2019/08/27/1566877767564-min_d.png")

    local tabBar = require('MMLuaKitGallery.TabToolBar'):new()
    tabBar:setupItems(normalImages, selectImages)
    MainLayout._tabBar = tabBar
    containerView:addView(tabBar.contentView)
end


---@private
function setupHomePagerView()
    local containerView = LinearLayout(LinearType.VERTICAL):width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT)
    MainLayout._homePagerContainerView = containerView
    MainLayout._tabBarContentView:addView(MainLayout._homePagerContainerView)
    local placeHolderView = View():bgColor(Color(255, 255, 255, 0.0)):width(window:width()):height(0.5)
    MainLayout._homePagerContainerView:addView(placeHolderView)

    local titles = Array()
    titles:add("关注")
    titles:add("推荐")
    local tabSegement = TabSegmentView(Rect(0, 0, window:width(), _NaviBarHeight), titles, _Color.Black)
    tabSegement:selectScale(1.0):width(MeasurementType.MATCH_PARENT):setAlignment(TabSegmentAlignment.CENTER):setGravity(Gravity.CENTER_HORIZONTAL)
    tabSegement:setAlignment(TabSegmentAlignment.CENTER)
    MainLayout._homePagerSegement = tabSegement
    MainLayout._homePagerContainerView:addView(tabSegement)

    local viewPager = ViewPager()
    viewPager:scrollToPage(1,false)
    viewPager:width(window:width()):height(MeasurementType.MATCH_PARENT):setGravity(Gravity.CENTER_HORIZONTAL)
    viewPager:showIndicator(false)
    MainLayout._homePagerContainerView:addView(viewPager)
    MainLayout._homePagerViewPager = viewPager;

    local viewPagerAdapter = ViewPagerAdapter()
    viewPagerAdapter:getCount(function(_)
        return 2
    end)

    viewPagerAdapter:initCell(function(cell, pos)
        local tableViewClass = require('MMLuaKitGallery.HomeTableView')
        local tableView = tableViewClass:new()
        cell._tableView = tableView --需持有tableView，否则会被GC
        if pos == 1 then
        cell._tableView:updateCategoryId(1)
        cell.contentView:addView(tableView:tableView(tableView.TYPE_FOLLOW))
        else
        cell._tableView:updateCategoryId(4)
        cell.contentView:addView(tableView:tableView(tableView.TYPE_RECOMMEND))
        end
    end)

    viewPagerAdapter:fillCellData(function(cell, pos)
        if pos == 1 then
            cell._tableView:updateCategoryId(1)
        else
            cell._tableView:updateCategoryId(4)
        end
    end)

    MainLayout._homePagerViewPager:adapter(viewPagerAdapter)
    MainLayout._homePagerSegement:relatedToViewPager(MainLayout._homePagerViewPager, true)
end

--- 加载主页面布局
setup()

