---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _name = 'HomePagerView',
    _version = '1.0'
}

---@public
function _class:new()
    local o = {}
    setmetatable(o, {__index = self})
    return o
end

---@public
---@return View containerView
function _class:rootView()
    if MainLayout._homePagerContainerView then
        return MainLayout._homePagerContainerView
    end
    self:setupViewPagerAdapter()
    return MainLayout._homePagerContainerView
end


return _class
