---
--- Generated by MLN Team (http://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 2019-09-05 12:05
---

local _class = {
    _name = "TabContainerView",
    _version = "1.0",
    _subViews = { },
    _subViewNames = { 'MMLuaKitGallery.HomePagerView',
                      'MMLuaKitGallery.DiscoverPagerView',
                      'MMLuaKitGallery.PlaceholderPagerView',
                      'MMLuaKitGallery.MessagePagerView',
                      'MMLuaKitGallery.MinePagerView' },
}

---入口
---@public
function _class:setup()
    --默认展示第一页
    self:display(1)
    self:setupTabarAction()
end

---配置tabBar
---@private
function _class:setupTabarAction()
    MainLayout._tabBar:setClickCallback(function(idx)
        if idx == 3 then
            Toast("打开照相机📷", 1)
        else
            self:display(idx)
        end
    end)
end

---展示View逻辑
---@private
function _class:display(index)
    if self.prevSelectedView then
        self.prevSelectedView:rootView():removeFromSuper()
    end
    self.prevSelectedView = self._subViews[index]

    if not self.prevSelectedView then
        self.prevSelectedView = require(self._subViewNames[index]):new()
        self._subViews[index] = self.prevSelectedView
    end
    MainLayout._tabBarContentView:addView(self.prevSelectedView:rootView())
end

return _class






