// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBDisplayItem.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class pbdisplayitem;
@class pbrect;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PbdisplayItemRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PbdisplayItemRoot : GPBRootObject
@end

#pragma mark - pbdisplayitem

typedef GPB_ENUM(pbdisplayitem_FieldNumber) {
  pbdisplayitem_FieldNumber_SubitemsArray = 1,
  pbdisplayitem_FieldNumber_IsHidden = 2,
  pbdisplayitem_FieldNumber_Alpha = 3,
  pbdisplayitem_FieldNumber_Frame = 4,
  pbdisplayitem_FieldNumber_Bounds = 5,
  pbdisplayitem_FieldNumber_SoloScreenshot = 6,
};

@interface pbdisplayitem : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<pbdisplayitem*> *subitemsArray;
/** The number of items in @c subitemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger subitemsArray_Count;

@property(nonatomic, readwrite) BOOL isHidden;

@property(nonatomic, readwrite) float alpha;

@property(nonatomic, readwrite, strong, null_resettable) pbrect *frame;
/** Test to see if @c frame has been set. */
@property(nonatomic, readwrite) BOOL hasFrame;

@property(nonatomic, readwrite, strong, null_resettable) pbrect *bounds;
/** Test to see if @c bounds has been set. */
@property(nonatomic, readwrite) BOOL hasBounds;

@property(nonatomic, readwrite, strong, null_resettable) pbrect *soloScreenshot;
/** Test to see if @c soloScreenshot has been set. */
@property(nonatomic, readwrite) BOOL hasSoloScreenshot;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
