// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLookinAttrIdentifiers.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PBLookinAttrGroupIdentifier

typedef GPB_ENUM(PBLookinAttrGroupIdentifier) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBLookinAttrGroupIdentifier_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** PBLookinAttrGroup_None = \@"n"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupNone = 0,

  /** PBLookinAttrGroup_Class = \@"c"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupClass = 1,

  /** PBLookinAttrGroup_Relation = \@"r"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupRelation = 2,

  /** PBLookinAttrGroup_Layout = \@"l"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupLayout = 3,

  /** PBLookinAttrGroup_AutoLayout = \@"a"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupAutoLayout = 4,

  /** PBLookinAttrGroup_ViewLayer = \@"vl"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupViewLayer = 5,

  /** PBLookinAttrGroup_UIImageView = \@"i"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUiimageView = 6,

  /** PBLookinAttrGroup_UILabel = \@"la"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUilabel = 7,

  /** PBLookinAttrGroup_UIControl = \@"co"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUicontrol = 8,

  /** PBLookinAttrGroup_UIButton = \@"b"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUibutton = 9,

  /** PBLookinAttrGroup_UIScrollView = \@"s"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUiscrollView = 10,

  /** PBLookinAttrGroup_UITableView = \@"ta"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUitableView = 11,

  /** PBLookinAttrGroup_UITextView = \@"te"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUitextView = 12,

  /** PBLookinAttrGroup_UITextField = \@"tf"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUitextField = 13,

  /** PBLookinAttrGroup_UIVisualEffectView = \@"ve"; */
  PBLookinAttrGroupIdentifier_PblookinAttrGroupUivisualEffectView = 14,
};

GPBEnumDescriptor *PBLookinAttrGroupIdentifier_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBLookinAttrGroupIdentifier_IsValidValue(int32_t value);

#pragma mark - Enum PBLookinAttrSectionIdentifier

typedef GPB_ENUM(PBLookinAttrSectionIdentifier) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBLookinAttrSectionIdentifier_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** PBLookinAttrSec_None = \@"n"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecNone = 0,

  /** PBLookinAttrSec_Class_Class = \@"cl_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecClassClass = 1,

  /** PBLookinAttrSec_Relation_Relation = \@"r_r"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecRelationRelation = 2,

  /** PBLookinAttrSec_Layout_Frame = \@"l_f"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecLayoutFrame = 3,

  /** PBLookinAttrSec_Layout_Bounds = \@"l_b"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecLayoutBounds = 4,

  /** PBLookinAttrSec_Layout_SafeArea = \@"l_s"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecLayoutSafeArea = 5,

  /** PBLookinAttrSec_Layout_Position = \@"l_p"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecLayoutPosition = 6,

  /** PBLookinAttrSec_Layout_AnchorPoint = \@"l_a"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecLayoutAnchorPoint = 7,

  /** PBLookinAttrSec_AutoLayout_Hugging = \@"a_h"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecAutoLayoutHugging = 8,

  /** PBLookinAttrSec_AutoLayout_Resistance = \@"a_r"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecAutoLayoutResistance = 9,

  /** PBLookinAttrSec_AutoLayout_Constraints = \@"a_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecAutoLayoutConstraints = 10,

  /** PBLookinAttrSec_AutoLayout_IntrinsicSize = \@"a_i"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecAutoLayoutIntrinsicSize = 11,

  /** PBLookinAttrSec_ViewLayer_Visibility = \@"v_v"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerVisibility = 12,

  /** PBLookinAttrSec_ViewLayer_InterationAndMasks = \@"v_i"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerInterationAndMasks = 13,

  /** PBLookinAttrSec_ViewLayer_Corner = \@"v_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerCorner = 14,

  /** PBLookinAttrSec_ViewLayer_BgColor = \@"v_b"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerBgColor = 15,

  /** PBLookinAttrSec_ViewLayer_Border = \@"v_bo"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerBorder = 16,

  /** PBLookinAttrSec_ViewLayer_Shadow = \@"v_s"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerShadow = 17,

  /** PBLookinAttrSec_ViewLayer_ContentMode = \@"v_co"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerContentMode = 18,

  /** PBLookinAttrSec_ViewLayer_TintColor = \@"v_t"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerTintColor = 19,

  /** PBLookinAttrSec_ViewLayer_Tag = \@"v_ta"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecViewLayerTag = 20,

  /** PBLookinAttrSec_UIImageView_Name = \@"i_n"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiimageViewName = 21,

  /** PBLookinAttrSec_UIImageView_Open = \@"i_o"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiimageViewOpen = 22,

  /** PBLookinAttrSec_UILabel_Text = \@"lb_t"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelText = 23,

  /** PBLookinAttrSec_UILabel_Font = \@"lb_f"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelFont = 24,

  /** PBLookinAttrSec_UILabel_NumberOfLines = \@"lb_n"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelNumberOfLines = 25,

  /** PBLookinAttrSec_UILabel_TextColor = \@"lb_tc"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelTextColor = 26,

  /** PBLookinAttrSec_UILabel_BreakMode = \@"lb_b"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelBreakMode = 27,

  /** PBLookinAttrSec_UILabel_Alignment = \@"lb_a"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelAlignment = 28,

  /** PBLookinAttrSec_UILabel_CanAdjustFont = \@"lb_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUilabelCanAdjustFont = 29,

  /** PBLookinAttrSec_UIControl_EnabledSelected = \@"c_e"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUicontrolEnabledSelected = 30,

  /** PBLookinAttrSec_UIControl_VerAlignment = \@"c_v"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUicontrolVerAlignment = 31,

  /** PBLookinAttrSec_UIControl_HorAlignment = \@"c_h"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUicontrolHorAlignment = 32,

  /** PBLookinAttrSec_UIControl_QMUIOutsideEdge = \@"c_o"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUicontrolQmuioutsideEdge = 33,

  /** PBLookinAttrSec_UIButton_ContentInsets = \@"b_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUibuttonContentInsets = 34,

  /** PBLookinAttrSec_UIButton_TitleInsets = \@"b_t"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUibuttonTitleInsets = 35,

  /** PBLookinAttrSec_UIButton_ImageInsets = \@"b_i"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUibuttonImageInsets = 36,

  /** PBLookinAttrSec_UIScrollView_ContentInset = \@"s_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewContentInset = 37,

  /** PBLookinAttrSec_UIScrollView_AdjustedInset = \@"s_a"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewAdjustedInset = 38,

  /** PBLookinAttrSec_UIScrollView_IndicatorInset = \@"s_i"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewIndicatorInset = 39,

  /** PBLookinAttrSec_UIScrollView_Offset = \@"s_o"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewOffset = 40,

  /** PBLookinAttrSec_UIScrollView_ContentSize = \@"s_cs"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewContentSize = 41,

  /** PBLookinAttrSec_UIScrollView_Behavior = \@"s_b"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewBehavior = 42,

  /** PBLookinAttrSec_UIScrollView_ShowsIndicator = \@"s_si"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewShowsIndicator = 43,

  /** PBLookinAttrSec_UIScrollView_Bounce = \@"s_bo"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewBounce = 44,

  /** PBLookinAttrSec_UIScrollView_ScrollPaging = \@"s_s"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewScrollPaging = 45,

  /** PBLookinAttrSec_UIScrollView_ContentTouches = \@"s_ct"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewContentTouches = 46,

  /** PBLookinAttrSec_UIScrollView_Zoom = \@"s_z"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewZoom = 47,

  /** PBLookinAttrSec_UIScrollView_QMUIInitialInset = \@"s_ii"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUiscrollViewQmuiinitialInset = 48,

  /** PBLookinAttrSec_UITableView_Style = \@"t_s"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewStyle = 49,

  /** PBLookinAttrSec_UITableView_SectionsNumber = \@"t_sn"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewSectionsNumber = 50,

  /** PBLookinAttrSec_UITableView_RowsNumber = \@"t_r"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewRowsNumber = 51,

  /** PBLookinAttrSec_UITableView_SeparatorStyle = \@"t_ss"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewSeparatorStyle = 52,

  /** PBLookinAttrSec_UITableView_SeparatorColor = \@"t_sc"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewSeparatorColor = 53,

  /** PBLookinAttrSec_UITableView_SeparatorInset = \@"t_si"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitableViewSeparatorInset = 54,

  /** PBLookinAttrSec_UITextView_Basic = \@"tv_b"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewBasic = 55,

  /** PBLookinAttrSec_UITextView_Text = \@"tv_t"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewText = 56,

  /** PBLookinAttrSec_UITextView_Font = \@"tv_f"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewFont = 57,

  /** PBLookinAttrSec_UITextView_TextColor = \@"tv_tc"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewTextColor = 58,

  /** PBLookinAttrSec_UITextView_Alignment = \@"tv_a"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewAlignment = 59,

  /** PBLookinAttrSec_UITextView_ContainerInset = \@"tv_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextViewContainerInset = 60,

  /** PBLookinAttrSec_UITextField_Text = \@"tf_t"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldText = 61,

  /** PBLookinAttrSec_UITextField_Placeholder = \@"tf_p"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldPlaceholder = 62,

  /** PBLookinAttrSec_UITextField_Font = \@"tf_f"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldFont = 63,

  /** PBLookinAttrSec_UITextField_TextColor = \@"tf_tc"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldTextColor = 64,

  /** PBLookinAttrSec_UITextField_Alignment = \@"tf_a"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldAlignment = 65,

  /** PBLookinAttrSec_UITextField_Clears = \@"tf_c"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldClears = 66,

  /** PBLookinAttrSec_UITextField_CanAdjustFont = \@"tf_ca"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldCanAdjustFont = 67,

  /** PBLookinAttrSec_UITextField_ClearButtonMode = \@"tf_cb"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUitextFieldClearButtonMode = 68,

  /** PBLookinAttrSec_UIVisualEffectView_Style = \@"ve_s"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUivisualEffectViewStyle = 69,

  /** PBLookinAttrSec_UIVisualEffectView_QMUIForegroundColor = \@"ve_f"; */
  PBLookinAttrSectionIdentifier_PblookinAttrSecUivisualEffectViewQmuiforegroundColor = 70,
};

GPBEnumDescriptor *PBLookinAttrSectionIdentifier_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBLookinAttrSectionIdentifier_IsValidValue(int32_t value);

#pragma mark - Enum PBLookinAttrIdentifier

typedef GPB_ENUM(PBLookinAttrIdentifier) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBLookinAttrIdentifier_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** PBLookinAttr_None = \@"n"; */
  PBLookinAttrIdentifier_PblookinAttrNone = 0,

  /** PBLookinAttr_Class_Class_Class = \@"c_c_c"; */
  PBLookinAttrIdentifier_PblookinAttrClassClassClass = 1,

  /** PBLookinAttr_Relation_Relation_Relation = \@"r_r_r"; */
  PBLookinAttrIdentifier_PblookinAttrRelationRelationRelation = 2,

  /** PBLookinAttr_Layout_Frame_Frame = \@"l_f_f"; */
  PBLookinAttrIdentifier_PblookinAttrLayoutFrameFrame = 3,

  /** PBLookinAttr_Layout_Bounds_Bounds = \@"l_b_b"; */
  PBLookinAttrIdentifier_PblookinAttrLayoutBoundsBounds = 4,

  /** PBLookinAttr_Layout_SafeArea_SafeArea = \@"l_s_s"; */
  PBLookinAttrIdentifier_PblookinAttrLayoutSafeAreaSafeArea = 5,

  /** PBLookinAttr_Layout_Position_Position = \@"l_p_p"; */
  PBLookinAttrIdentifier_PblookinAttrLayoutPositionPosition = 6,

  /** PBLookinAttr_Layout_AnchorPoint_AnchorPoint = \@"l_a_a"; */
  PBLookinAttrIdentifier_PblookinAttrLayoutAnchorPointAnchorPoint = 7,

  /** PBLookinAttr_AutoLayout_Hugging_Hor = \@"al_h_h"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutHuggingHor = 8,

  /** PBLookinAttr_AutoLayout_Hugging_Ver = \@"al_h_v"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutHuggingVer = 9,

  /** PBLookinAttr_AutoLayout_Resistance_Hor = \@"al_r_h"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutResistanceHor = 10,

  /** PBLookinAttr_AutoLayout_Resistance_Ver = \@"al_r_v"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutResistanceVer = 11,

  /** PBLookinAttr_AutoLayout_Constraints_Constraints = \@"al_c_c"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutConstraintsConstraints = 12,

  /** PBLookinAttr_AutoLayout_IntrinsicSize_Size = \@"cl_i_s"; */
  PBLookinAttrIdentifier_PblookinAttrAutoLayoutIntrinsicSizeSize = 13,

  /** PBLookinAttr_ViewLayer_Visibility_Hidden = \@"vl_v_h"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerVisibilityHidden = 14,

  /** PBLookinAttr_ViewLayer_Visibility_Opacity = \@"vl_v_o"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerVisibilityOpacity = 15,

  /** PBLookinAttr_ViewLayer_InterationAndMasks_Interaction = \@"vl_i_i"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerInterationAndMasksInteraction = 16,

  /** PBLookinAttr_ViewLayer_InterationAndMasks_MasksToBounds = \@"vl_i_m"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerInterationAndMasksMasksToBounds = 17,

  /** PBLookinAttr_ViewLayer_Corner_Radius = \@"vl_c_r"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerCornerRadius = 18,

  /** PBLookinAttr_ViewLayer_BgColor_BgColor = \@"vl_b_b"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerBgColorBgColor = 19,

  /** PBLookinAttr_ViewLayer_Border_Color = \@"vl_b_c"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerBorderColor = 20,

  /** PBLookinAttr_ViewLayer_Border_Width = \@"vl_b_w"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerBorderWidth = 21,

  /** PBLookinAttr_ViewLayer_Shadow_Color = \@"vl_s_c"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerShadowColor = 22,

  /** PBLookinAttr_ViewLayer_Shadow_Opacity = \@"vl_s_o"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerShadowOpacity = 23,

  /** PBLookinAttr_ViewLayer_Shadow_Radius = \@"vl_s_r"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerShadowRadius = 24,

  /** PBLookinAttr_ViewLayer_Shadow_OffsetW = \@"vl_s_ow"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerShadowOffsetW = 25,

  /** PBLookinAttr_ViewLayer_Shadow_OffsetH = \@"vl_s_oh"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerShadowOffsetH = 26,

  /** PBLookinAttr_ViewLayer_ContentMode_Mode = \@"vl_c_m"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerContentModeMode = 27,

  /** PBLookinAttr_ViewLayer_TintColor_Color = \@"vl_t_c"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerTintColorColor = 28,

  /** PBLookinAttr_ViewLayer_TintColor_Mode = \@"vl_t_m"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerTintColorMode = 29,

  /** PBLookinAttr_ViewLayer_Tag_Tag = \@"vl_t_t"; */
  PBLookinAttrIdentifier_PblookinAttrViewLayerTagTag = 30,

  /** PBLookinAttr_UIImageView_Name_Name = \@"iv_n_n"; */
  PBLookinAttrIdentifier_PblookinAttrUiimageViewNameName = 31,

  /** PBLookinAttr_UIImageView_Open_Open = \@"iv_o_o"; */
  PBLookinAttrIdentifier_PblookinAttrUiimageViewOpenOpen = 32,

  /** PBLookinAttr_UILabel_Text_Text = \@"lb_t_t"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelTextText = 33,

  /** PBLookinAttr_UILabel_Font_Name = \@"lb_f_n"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelFontName = 34,

  /** PBLookinAttr_UILabel_Font_Size = \@"lb_f_s"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelFontSize = 35,

  /** PBLookinAttr_UILabel_NumberOfLines_NumberOfLines = \@"lb_n_n"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelNumberOfLinesNumberOfLines = 36,

  /** PBLookinAttr_UILabel_TextColor_Color = \@"lb_t_c"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelTextColorColor = 37,

  /** PBLookinAttr_UILabel_Alignment_Alignment = \@"lb_a_a"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelAlignmentAlignment = 38,

  /** PBLookinAttr_UILabel_BreakMode_Mode = \@"lb_b_m"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelBreakModeMode = 39,

  /** PBLookinAttr_UILabel_CanAdjustFont_CanAdjustFont = \@"lb_c_c"; */
  PBLookinAttrIdentifier_PblookinAttrUilabelCanAdjustFontCanAdjustFont = 40,

  /** PBLookinAttr_UIControl_EnabledSelected_Enabled = \@"ct_e_e"; */
  PBLookinAttrIdentifier_PblookinAttrUicontrolEnabledSelectedEnabled = 41,

  /** PBLookinAttr_UIControl_EnabledSelected_Selected = \@"ct_e_s"; */
  PBLookinAttrIdentifier_PblookinAttrUicontrolEnabledSelectedSelected = 42,

  /** PBLookinAttr_UIControl_VerAlignment_Alignment = \@"ct_v_a"; */
  PBLookinAttrIdentifier_PblookinAttrUicontrolVerAlignmentAlignment = 43,

  /** PBLookinAttr_UIControl_HorAlignment_Alignment = \@"ct_h_a"; */
  PBLookinAttrIdentifier_PblookinAttrUicontrolHorAlignmentAlignment = 44,

  /** PBLookinAttr_UIControl_QMUIOutsideEdge_Edge = \@"ct_o_e"; */
  PBLookinAttrIdentifier_PblookinAttrUicontrolQmuioutsideEdgeEdge = 45,

  /** PBLookinAttr_UIButton_ContentInsets_Insets = \@"bt_c_i"; */
  PBLookinAttrIdentifier_PblookinAttrUibuttonContentInsetsInsets = 46,

  /** PBLookinAttr_UIButton_TitleInsets_Insets = \@"bt_t_i"; */
  PBLookinAttrIdentifier_PblookinAttrUibuttonTitleInsetsInsets = 47,

  /** PBLookinAttr_UIButton_ImageInsets_Insets = \@"bt_i_i"; */
  PBLookinAttrIdentifier_PblookinAttrUibuttonImageInsetsInsets = 48,

  /** PBLookinAttr_UIScrollView_Offset_Offset = \@"sv_o_o"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewOffsetOffset = 49,

  /** PBLookinAttr_UIScrollView_ContentSize_Size = \@"sv_c_s"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewContentSizeSize = 50,

  /** PBLookinAttr_UIScrollView_ContentInset_Inset = \@"sv_c_i"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewContentInsetInset = 51,

  /** PBLookinAttr_UIScrollView_AdjustedInset_Inset = \@"sv_a_i"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewAdjustedInsetInset = 52,

  /** PBLookinAttr_UIScrollView_Behavior_Behavior = \@"sv_b_b"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewBehaviorBehavior = 53,

  /** PBLookinAttr_UIScrollView_IndicatorInset_Inset = \@"sv_i_i"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewIndicatorInsetInset = 54,

  /** PBLookinAttr_UIScrollView_ScrollPaging_ScrollEnabled = \@"sv_s_s"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewScrollPagingScrollEnabled = 55,

  /** PBLookinAttr_UIScrollView_ScrollPaging_PagingEnabled = \@"sv_s_p"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewScrollPagingPagingEnabled = 56,

  /** PBLookinAttr_UIScrollView_Bounce_Ver = \@"sv_b_v"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewBounceVer = 57,

  /** PBLookinAttr_UIScrollView_Bounce_Hor = \@"sv_b_h"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewBounceHor = 58,

  /** PBLookinAttr_UIScrollView_ShowsIndicator_Hor = \@"sv_h_h"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewShowsIndicatorHor = 59,

  /** PBLookinAttr_UIScrollView_ShowsIndicator_Ver = \@"sv_s_v"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewShowsIndicatorVer = 60,

  /** PBLookinAttr_UIScrollView_ContentTouches_Delay = \@"sv_c_d"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewContentTouchesDelay = 61,

  /** PBLookinAttr_UIScrollView_ContentTouches_CanCancel = \@"sv_c_c"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewContentTouchesCanCancel = 62,

  /** PBLookinAttr_UIScrollView_Zoom_MinScale = \@"sv_z_mi"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewZoomMinScale = 63,

  /** PBLookinAttr_UIScrollView_Zoom_MaxScale = \@"sv_z_ma"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewZoomMaxScale = 64,

  /** PBLookinAttr_UIScrollView_Zoom_Scale = \@"sv_z_s"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewZoomScale = 65,

  /** PBLookinAttr_UIScrollView_Zoom_Bounce = \@"sv_z_b"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewZoomBounce = 66,

  /** PBLookinAttr_UIScrollView_QMUIInitialInset_Inset = \@"sv_qi_i"; */
  PBLookinAttrIdentifier_PblookinAttrUiscrollViewQmuiinitialInsetInset = 67,

  /** PBLookinAttr_UITableView_Style_Style = \@"tv_s_s"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewStyleStyle = 68,

  /** PBLookinAttr_UITableView_SectionsNumber_Number = \@"tv_s_n"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewSectionsNumberNumber = 69,

  /** PBLookinAttr_UITableView_RowsNumber_Number = \@"tv_r_n"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewRowsNumberNumber = 70,

  /** PBLookinAttr_UITableView_SeparatorInset_Inset = \@"tv_s_i"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewSeparatorInsetInset = 71,

  /** PBLookinAttr_UITableView_SeparatorColor_Color = \@"tv_s_c"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewSeparatorColorColor = 72,

  /** PBLookinAttr_UITableView_SeparatorStyle_Style = \@"tv_ss_s"; */
  PBLookinAttrIdentifier_PblookinAttrUitableViewSeparatorStyleStyle = 73,

  /** PBLookinAttr_UITextView_Font_Name = \@"te_f_n"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewFontName = 74,

  /** PBLookinAttr_UITextView_Font_Size = \@"te_f_s"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewFontSize = 75,

  /** PBLookinAttr_UITextView_Basic_Editable = \@"te_b_e"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewBasicEditable = 76,

  /** PBLookinAttr_UITextView_Basic_Selectable = \@"te_b_s"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewBasicSelectable = 77,

  /** PBLookinAttr_UITextView_Text_Text = \@"te_t_t"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewTextText = 78,

  /** PBLookinAttr_UITextView_TextColor_Color = \@"te_t_c"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewTextColorColor = 79,

  /** PBLookinAttr_UITextView_Alignment_Alignment = \@"te_a_a"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewAlignmentAlignment = 80,

  /** PBLookinAttr_UITextView_ContainerInset_Inset = \@"te_c_i"; */
  PBLookinAttrIdentifier_PblookinAttrUitextViewContainerInsetInset = 81,

  /** PBLookinAttr_UITextField_Text_Text = \@"tf_t_t"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldTextText = 82,

  /** PBLookinAttr_UITextField_Placeholder_Placeholder = \@"tf_p_p"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldPlaceholderPlaceholder = 83,

  /** PBLookinAttr_UITextField_Font_Name = \@"tf_f_n"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldFontName = 84,

  /** PBLookinAttr_UITextField_Font_Size = \@"tf_f_s"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldFontSize = 85,

  /** PBLookinAttr_UITextField_TextColor_Color = \@"tf_t_c"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldTextColorColor = 86,

  /** PBLookinAttr_UITextField_Alignment_Alignment = \@"tf_a_a"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldAlignmentAlignment = 87,

  /** PBLookinAttr_UITextField_Clears_ClearsOnBeginEditing = \@"tf_c_c"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldClearsClearsOnBeginEditing = 88,

  /** PBLookinAttr_UITextField_Clears_ClearsOnInsertion = \@"tf_c_co"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldClearsClearsOnInsertion = 89,

  /** PBLookinAttr_UITextField_CanAdjustFont_CanAdjustFont = \@"tf_c_ca"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldCanAdjustFontCanAdjustFont = 90,

  /** PBLookinAttr_UITextField_CanAdjustFont_MinSize = \@"tf_c_m"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldCanAdjustFontMinSize = 91,

  /** PBLookinAttr_UITextField_ClearButtonMode_Mode = \@"tf_cb_m"; */
  PBLookinAttrIdentifier_PblookinAttrUitextFieldClearButtonModeMode = 92,

  /** PBLookinAttr_UIVisualEffectView_Style_Style = \@"ve_s_s"; */
  PBLookinAttrIdentifier_PblookinAttrUivisualEffectViewStyleStyle = 93,

  /** PBLookinAttr_UIVisualEffectView_QMUIForegroundColor_Color = \@"ve_f_c"; */
  PBLookinAttrIdentifier_PblookinAttrUivisualEffectViewQmuiforegroundColorColor = 94,
};

GPBEnumDescriptor *PBLookinAttrIdentifier_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBLookinAttrIdentifier_IsValidValue(int32_t value);

#pragma mark - PblookinAttrIdentifiersRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PblookinAttrIdentifiersRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
