// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLookinValueType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class pbcolor;
@class pbpoint;
@class pbrect;
@class pbsize;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PblookinValueTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PblookinValueTypeRoot : GPBRootObject
@end

#pragma mark - pblookinvaluetype

typedef GPB_ENUM(pblookinvaluetype_FieldNumber) {
  pblookinvaluetype_FieldNumber_IntValue = 1,
  pblookinvaluetype_FieldNumber_LongValue = 2,
  pblookinvaluetype_FieldNumber_UnsignedIntValue = 3,
  pblookinvaluetype_FieldNumber_UnsignedLongValue = 4,
  pblookinvaluetype_FieldNumber_FloatValue = 5,
  pblookinvaluetype_FieldNumber_DoubleValue = 6,
  pblookinvaluetype_FieldNumber_BoolValue = 7,
  pblookinvaluetype_FieldNumber_PointValue = 8,
  pblookinvaluetype_FieldNumber_SizeValue = 9,
  pblookinvaluetype_FieldNumber_RectValue = 10,
  pblookinvaluetype_FieldNumber_StringValue = 11,
  pblookinvaluetype_FieldNumber_ColorValue = 12,
};

/**
 *
 * noneValue = 0;
 * voidValue = 1;
 * charValue = 2;
 * intValue = 3;
 * shortValue = 4;
 * longValue = 5;
 * longLongValue = 6;
 * unsignedCharValue = 7;
 * unsignedIntValue = 8;
 * unsignedShortValue = 9;
 * unsignedLongValue = 10;
 * unsignedLongLongValue = 11;
 * floatValue = 12;
 * doubleValue = 13;
 * boolValue = 14;
 * selValue = 15;
 * classValue = 16;
 * pointValue = 17;
 * vectorValue = 18;
 * sizeValue = 19;
 * rectValue = 20;
 * affineTransformValue = 21;
 * UIEdgeInsetsValue = 22;
 * UIOffsetValue = 23;
 * stringValue = 24;
 * enumIntValue = 25;
 * enumLongValue = 26;
 * /// Value 实际为 RGBA 数组，即 \@[NSNumber, NSNumber, NSNumber, NSNumber]，NSNumber 范围是 0 ~ 1
 * colorValue = 27;
 * /// 业务需要根据具体的 AttrIdentifier 来解析
 * customObjValue = 28;
 **/
@interface pblookinvaluetype : GPBMessage

/**
 *
 * 已有类型
 * int32 intValue = 3;
 * int64 longValue = 5;
 * uint32 unsignedIntValue = 8;
 * uint64 unsignedLongValue = 9;
 * float floatValue = 12;
 * double doubleValue = 13;
 * bool boolValue = 14;
 * pbpoint pointValue = 17;
 * pbsize sizeValue = 19;
 * pbrect rectValue = 20;
 * string stringValue = 24;
 * pbcolor colorValue = 27;
 **/
@property(nonatomic, readwrite) int32_t intValue;

@property(nonatomic, readwrite) int64_t longValue;

@property(nonatomic, readwrite) uint32_t unsignedIntValue;

@property(nonatomic, readwrite) uint64_t unsignedLongValue;

@property(nonatomic, readwrite) float floatValue;

@property(nonatomic, readwrite) double doubleValue;

@property(nonatomic, readwrite) BOOL boolValue;

@property(nonatomic, readwrite, strong, null_resettable) pbpoint *pointValue;
/** Test to see if @c pointValue has been set. */
@property(nonatomic, readwrite) BOOL hasPointValue;

@property(nonatomic, readwrite, strong, null_resettable) pbsize *sizeValue;
/** Test to see if @c sizeValue has been set. */
@property(nonatomic, readwrite) BOOL hasSizeValue;

@property(nonatomic, readwrite, strong, null_resettable) pbrect *rectValue;
/** Test to see if @c rectValue has been set. */
@property(nonatomic, readwrite) BOOL hasRectValue;

@property(nonatomic, readwrite, copy, null_resettable) NSString *stringValue;

@property(nonatomic, readwrite, strong, null_resettable) pbcolor *colorValue;
/** Test to see if @c colorValue has been set. */
@property(nonatomic, readwrite) BOOL hasColorValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
