// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLookinAttribute.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class pblookinvaluetype;
GPB_ENUM_FWD_DECLARE(PBLookinAttrIdentifier);
GPB_ENUM_FWD_DECLARE(PBLookinAttrType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PblookinAttributeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PblookinAttributeRoot : GPBRootObject
@end

#pragma mark - pblookinattribute

typedef GPB_ENUM(pblookinattribute_FieldNumber) {
  pblookinattribute_FieldNumber_Identifier = 1,
  pblookinattribute_FieldNumber_Title = 2,
  pblookinattribute_FieldNumber_Type = 3,
  pblookinattribute_FieldNumber_Value = 4,
};

@interface pblookinattribute : GPBMessage

@property(nonatomic, readwrite) enum PBLookinAttrIdentifier identifier;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) enum PBLookinAttrType type;

/**
 * 产生循环依赖，先注释掉
 * pbdisplayitem targetDisplayItem = 4;
 **/
@property(nonatomic, readwrite, strong, null_resettable) pblookinvaluetype *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

/**
 * Fetches the raw value of a @c pblookinattribute's @c identifier property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t pblookinattribute_Identifier_RawValue(pblookinattribute *message);
/**
 * Sets the raw value of an @c pblookinattribute's @c identifier property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setpblookinattribute_Identifier_RawValue(pblookinattribute *message, int32_t value);

/**
 * Fetches the raw value of a @c pblookinattribute's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t pblookinattribute_Type_RawValue(pblookinattribute *message);
/**
 * Sets the raw value of an @c pblookinattribute's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setpblookinattribute_Type_RawValue(pblookinattribute *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
