// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBLookinAttrType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PBLookinAttrType

typedef GPB_ENUM(PBLookinAttrType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBLookinAttrType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PBLookinAttrType_PblookinAttrTypeNone = 0,
  PBLookinAttrType_PblookinAttrTypeVoid = 1,
  PBLookinAttrType_PblookinAttrTypeChar = 2,
  PBLookinAttrType_PblookinAttrTypeInt = 3,
  PBLookinAttrType_PblookinAttrTypeShort = 4,
  PBLookinAttrType_PblookinAttrTypeLong = 5,
  PBLookinAttrType_PblookinAttrTypeLongLong = 6,
  PBLookinAttrType_PblookinAttrTypeUnsignedChar = 7,
  PBLookinAttrType_PblookinAttrTypeUnsignedInt = 8,
  PBLookinAttrType_PblookinAttrTypeUnsignedShort = 9,
  PBLookinAttrType_PblookinAttrTypeUnsignedLong = 10,
  PBLookinAttrType_PblookinAttrTypeUnsignedLongLong = 11,
  PBLookinAttrType_PblookinAttrTypeFloat = 12,
  PBLookinAttrType_PblookinAttrTypeDouble = 13,
  PBLookinAttrType_PblookinAttrTypeBool = 14,
  PBLookinAttrType_PblookinAttrTypeSel = 15,
  PBLookinAttrType_PblookinAttrTypeClass = 16,
  PBLookinAttrType_PblookinAttrTypeCgpoint = 17,
  PBLookinAttrType_PblookinAttrTypeCgvector = 18,
  PBLookinAttrType_PblookinAttrTypeCgsize = 19,
  PBLookinAttrType_PblookinAttrTypeCgrect = 20,
  PBLookinAttrType_PblookinAttrTypeCgaffineTransform = 21,
  PBLookinAttrType_PblookinAttrTypeUiedgeInsets = 22,
  PBLookinAttrType_PblookinAttrTypeUioffset = 23,
  PBLookinAttrType_PblookinAttrTypeNsstring = 24,
  PBLookinAttrType_PblookinAttrTypeEnumInt = 25,
  PBLookinAttrType_PblookinAttrTypeEnumLong = 26,

  /** / value 实际为 RGBA 数组，即 \@[NSNumber, NSNumber, NSNumber, NSNumber]，NSNumber 范围是 0 ~ 1 */
  PBLookinAttrType_PblookinAttrTypeUicolor = 27,

  /** / 业务需要根据具体的 AttrIdentifier 来解析 */
  PBLookinAttrType_PblookinAttrTypeCustomObj = 28,
};

GPBEnumDescriptor *PBLookinAttrType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBLookinAttrType_IsValidValue(int32_t value);

#pragma mark - PblookinAttrTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PblookinAttrTypeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
